services:
  db:
    image: postgres:16-alpine
    container_name: db_prod
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db
    ports:
      - '5432:5432'
    volumes:
      - postgres_data_prod:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  app:
    container_name: app_prod
    build:
      context: .
      dockerfile: Dockerfile.prod
      args:
        PORT: ${PORT:-3333}
        DATABASE_URL: ${DATABASE_URL}
    env_file:
      - path: ./.env
    ports:
      - '${PORT:-3333}:${PORT:-3333}'
    depends_on:
      db:
        condition: service_healthy
        required: false
    restart: unless-stopped

  adminer:
    image: adminer:latest
    container_name: adminer_prod
    ports:
      - '8080:8080'
    environment:
      ADMINER_DEFAULT_SERVER: db
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped

volumes:
  postgres_data_prod:
