// Auto-generated by Vitek - DO NOT EDIT
// This file is automatically generated from your API routes

export type VitekParams = Record<string, string>;
export type VitekQuery = Record<string, string | string[]>;


export interface HealthGetParams extends VitekParams {

}

export type VitekRoute =
  | {
      pattern: 'health';
      method: 'get';
      params: HealthGetParams;
    };

export const API_BASE_PATH = '/api' as const;
