// Auto-generated by Vitek - DO NOT EDIT
// This file is automatically generated from your API routes

import { API_BASE_PATH } from './api.types';

export async function getHealth(options?: RequestInit): Promise<any> {
  return fetch(`${API_BASE_PATH}/health`, {
    method: 'GET',
    ...options,
  }).then(res => res.json());
}
